# -*- coding: utf-8 -*-
"""myfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e-V4gddIhN9kVunjOiHNkcsxjzHTuap
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Titulo del Proyecto')
st.write('Hola **como** estas')
